version: '3.8'

services:
  db:
    container_name: app_db
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=recipe_app_db
    ports:
      - 5432:5432